# Generated by Django 5.2.5 on 2025-08-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название прибора')),
                ('type', models.CharField(max_length=50, verbose_name='Тип прибора')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Серийный номер')),
                ('last_verification_date', models.DateField(verbose_name='Дата последней поверки')),
                ('next_verification_date', models.DateField(verbose_name='Дата следующей поверки')),
                ('first_notification_date', models.DateField(verbose_name='Первая дата уведомления (подготовка)')),
                ('second_notification_date', models.DateField(verbose_name='Вторая дата уведомления (заказ транспорта)')),
                ('department', models.CharField(max_length=100, verbose_name='Отдел')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('needs_verification', 'Требует поверки')], default='active', max_length=20, verbose_name='Статус')),
                ('passport_file', models.FileField(blank=True, null=True, upload_to='passports/', verbose_name='Паспорт прибора')),
                ('verification_result_file', models.FileField(blank=True, null=True, upload_to='verification_results/', verbose_name='Результат поверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Прибор',
                'verbose_name_plural': 'Приборы',
            },
        ),
    ]
